// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"backend/internal/database"
	"backend/internal/handlers"
	"backend/internal/routes"
	"backend/internal/services"
	"github.com/google/wire"
)

// Injectors from wire.go:

// InitializeContainer 初始化容器
func InitializeContainer(manager *database.Manager) (*Container, error) {
	taskRepository := ProvideTaskRepository(manager)
	taskService := services.NewTaskService(taskRepository)
	taskHandler := handlers.NewTaskHandler(taskService)
	userRepository := ProvideUserRepository(manager)
	userService := services.NewUserService(userRepository)
	userHandler := handlers.NewUserHandler(userService)
	healthService := services.NewHealthService()
	healthHandler := handlers.NewHealthHandler(healthService)
	handlersHandlers := &handlers.Handlers{
		Task:   taskHandler,
		User:   userHandler,
		Health: healthHandler,
	}
	router := routes.NewRouter(handlersHandlers)
	container := &Container{
		Router: router,
	}
	return container, nil
}

// wire.go:

var RepositorySet = wire.NewSet(
	ProvideTaskRepository,
	ProvideUserRepository,
)

var ServiceSet = wire.NewSet(services.NewTaskService, services.NewUserService, services.NewHealthService)

var HandlerSet = wire.NewSet(handlers.NewTaskHandler, handlers.NewUserHandler, handlers.NewHealthHandler, wire.Struct(new(handlers.Handlers), "*"))

var RouterSet = wire.NewSet(routes.NewRouter)
