/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Avatar: typeof import('antd').Avatar
  const Button: typeof import('antd').Button
  const Card: typeof import('antd').Card
  const Divider: typeof import('antd').Divider
  const Dropdown: typeof import('antd').Dropdown
  const Form: typeof import('antd').Form
  const Input: typeof import('antd').Input
  const Space: typeof import('antd').Space
  const message: typeof import('antd').message
}
